/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseWorkQueues;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthcareProviderEnterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthcareProviderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author divinity
 */
public class HealthcareWorkQueueJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthcareWorkQueueJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount account;
    private HealthcareProviderEnterprise healthCareEnterprise;

    public HealthcareWorkQueueJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.healthCareEnterprise = (HealthcareProviderEnterprise) enterprise;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        valueLabel.setText(healthCareEnterprise.getName());
        populateComboBox();
        populateRequestTable();
    }

    public void populateComboBox() {
        jComboResponse.removeAllItems();
        jComboResponse.addItem("Accept");
        jComboResponse.addItem("Reject");
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : healthCareEnterprise.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getSender();
            row[2] = request.getStatus();
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboResponse = new javax.swing.JComboBox();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        refreshTestJButton = new javax.swing.JButton();
        requestTestJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 225, 226));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboResponse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboResponseActionPerformed(evt);
            }
        });
        add(jComboResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 274, 148, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 8, 158, 26));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 6, -1, 30));

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 54, -1, -1));

        requestTestJButton.setText("Send >");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 273, 91, -1));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device", "Sender", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 101, 383, 126));

        jLabel1.setText("Select Response");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 251, -1, -1));

        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 329, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Request !!");
            return;
        }

        HealthcareProviderWorkRequest request = (HealthcareProviderWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if (request.getStatus().equalsIgnoreCase("Accept") || request.getStatus().equalsIgnoreCase("Reject")) {
            JOptionPane.showMessageDialog(null, "Request already processed.");
            return;
        }
        workRequestJTable.getValueAt(selectedRow, 0);
        String status = jComboResponse.getSelectedItem().toString();
        request.setStatus(status);
        if (request.getStatus().equalsIgnoreCase("Accept")) {
            request.setTestResult("Approved");
        } else {
            request.setTestResult("Rejected");
        }
        updateMnaufactureStatus(request);

    }//GEN-LAST:event_requestTestJButtonActionPerformed
    public void updateMnaufactureStatus(WorkRequest req) {
        String parentId = req.getParentId();
        System.out.println("Request id for doc  " + parentId);

        for (WorkRequest request : business.getAllWorkList()) {
            if (request.getRequestId().equalsIgnoreCase(parentId)) {
                request.setStatus(req.getStatus());
                break;
            }
        }

    }


    private void jComboResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboResponseActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox jComboResponse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
