/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeviceLabAssitantWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DeviceLabOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeviceLabLevelWorkRequest;
import Business.WorkQueue.DoctorLevelWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author divinity
 */
public class DeviceLabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private DeviceLabOrganization deviceLabOrganization;

    public DeviceLabAssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.deviceLabOrganization = (DeviceLabOrganization) organization;
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        System.out.println("before populate");
        populateTable();
        System.out.println("after populate");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : deviceLabOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            System.out.println("Request id:" + request.getRequestId());
            row[3] = request.getStatus();

            model.addRow(row);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        processJButton = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        fwdToDoctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 225, 226));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 95, 588, 102));

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 213, 172, -1));

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 213, 172, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 48, -1, -1));

        fwdToDoctor.setText("Forward to Doctor >");
        fwdToDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fwdToDoctorActionPerformed(evt);
            }
        });
        add(fwdToDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 213, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lab Assistant WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 6, -1, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a VALID Request !!");

        } else {
            WorkRequest request1 = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if ((request1.getReceiver() == null)) {
                JOptionPane.showMessageDialog(null, "Request can't be processed. Kindly assign it first.");
            } else {
                DeviceLabLevelWorkRequest request = (DeviceLabLevelWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);

                if (request.getStatus().equalsIgnoreCase("Rejected")) {
                    JOptionPane.showMessageDialog(null, "Request has already been processed.");
                } else if (request.getStatus().equalsIgnoreCase("Send to Doctor")) {
                    JOptionPane.showMessageDialog(null, "Request has already been processed. ");
                } else if (request.getStatus().equalsIgnoreCase("Pending Doctor Approval")) {
                    JOptionPane.showMessageDialog(null, "Already sent for Doctor Approval.");
                } else {
                    request.setStatus("Processing");
                    ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, request, business);
                    userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                }

            }
        }
    }//GEN-LAST:event_processJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Request !!");
            return;

        }
        //System.out.println("hello in assignment");

        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if (request.getReceiver() == null) {
            request.setReceiver(userAccount);
            request.setStatus("Pending");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Request Already Sent/Assigned.");
        }


    }//GEN-LAST:event_assignJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void fwdToDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fwdToDoctorActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            //System.out.println("found row as null");
            JOptionPane.showMessageDialog(null, "Please select a request to be forwarded");
            return;
        }
        WorkRequest requestObjForDeviceLab = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        DoctorLevelWorkRequest requestObjForDoctor = new DoctorLevelWorkRequest();
        //Devrequest = (DeviceLabLevelWorkRequest)request;

        if (requestObjForDeviceLab.getStatus().equalsIgnoreCase("Rejected")) {
            JOptionPane.showMessageDialog(null, "Device tests show: 'failed'. Cannot forward to Doctor.");
        } else if (requestObjForDeviceLab.getStatus().equalsIgnoreCase("Approved")) {
            JOptionPane.showMessageDialog(null, "Device is already approved.");
        } else if (requestObjForDeviceLab.getStatus().equalsIgnoreCase("Pending Doctor Approval")) {
            JOptionPane.showMessageDialog(null, "Already sent for Doctor Approval.");
        }else if (requestObjForDeviceLab.getStatus().equalsIgnoreCase("Send to Doctor")) {
            requestObjForDoctor.setDevice(requestObjForDeviceLab.getDevice());
            requestObjForDoctor.setEnterprise(requestObjForDeviceLab.getEnterprise());
            requestObjForDoctor.setSender(userAccount);
            requestObjForDoctor.setStatus("To Be Processed");
            requestObjForDoctor.setParentId(requestObjForDeviceLab.getRequestId());
            requestObjForDeviceLab.setStatus("Pending Doctor Approval");

            requestObjForDoctor.setParentRequestObject(requestObjForDeviceLab);
            requestObjForDeviceLab.setChildRequestObject(requestObjForDoctor);

            business.getAllWorkList().add(requestObjForDoctor);

            Organization org = null;
            Enterprise enterprise1 = null;

            for (Network net : business.getNetworkList()) {
                for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                    if (ent.equals(requestObjForDoctor.getEnterprise())) {
                        for (Organization org1 : ent.getOrganizationDirectory().getOrganizationList()) {
                            if (org1 instanceof DoctorOrganization) {
                                org = org1;
                                enterprise1 = ent;
                                break;
                            }
                        }
                        if (org != null && enterprise1 != null) {
                            org.getWorkQueue().getWorkRequestList().add(requestObjForDoctor);
                            userAccount.getWorkQueue().getWorkRequestList().add(requestObjForDeviceLab);
                            JOptionPane.showMessageDialog(null, "Device Sent to Doctor for final Approval !");
                            //System.out.println(dev);
                        }
                    }
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Update the device test status !");
        }

        populateTable();

        
    }//GEN-LAST:event_fwdToDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton fwdToDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
