/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeviceLabAssitantWorkArea;

import Business.EcoSystem;
import Business.WorkQueue.DeviceLabLevelWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author divinity
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private DeviceLabLevelWorkRequest request;
    private EcoSystem business;
    public ProcessWorkRequestJPanel( JPanel userProcessContainer, WorkRequest request, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = (DeviceLabLevelWorkRequest)request;
        this.business = business;
        populateTestResult();
        populateFDAApproval();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateTestResult(){
     jComboTestResult.removeAllItems();  
     jComboFDAApproval.removeAllItems();
     jComboTestResult.addItem("Pass");
     jComboTestResult.addItem("Fail");        
    }
    
    public void populateFDAApproval(){
        jComboFDAApproval.addItem("Yes");
        jComboFDAApproval.addItem("No");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboFDAApproval = new javax.swing.JComboBox();
        jComboTestResult = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(201, 218, 229));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Test Result:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 82, 94, -1));

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 138, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 235, -1, -1));

        jLabel2.setText("FDA Approved:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 54, -1, -1));

        jComboFDAApproval.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboFDAApproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 54, 131, -1));

        jComboTestResult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboTestResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTestResultActionPerformed(evt);
            }
        });
        add(jComboTestResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 93, 131, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Lab Assistant Work Requests");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 6, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        request.setTestResult(jComboTestResult.getSelectedItem().toString());
        request.setFDAApproved(jComboFDAApproval.getSelectedItem().toString());
        if((request.getTestResult().equalsIgnoreCase("Pass")) && request.getFDAApproved().equalsIgnoreCase("Yes"))
        {request.setStatus("Send to Doctor");
        JOptionPane.showMessageDialog(null, "Status updated, forward to Doctor.");
        }
        else {
          request.setStatus("Rejected");  
          updateRejectToAuth(request);
          JOptionPane.showMessageDialog(null, "Request status updated to Rejected.");
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed

        public void updateRejectToAuth(WorkRequest req){
         WorkRequest parentObj = req.getParentRequestObject();
         parentObj.setStatus(req.getStatus());    
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DeviceLabAssistantWorkAreaJPanel dwjp = (DeviceLabAssistantWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jComboTestResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTestResultActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboTestResultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox jComboFDAApproval;
    private javax.swing.JComboBox jComboTestResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
